spring:
  application:
    name: template-app
  # tpl:if environments
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  # tpl:endif
server:
  port: 8080
# tpl:if environments
app:
  environment: development
  verbose-errors: false
  cache-seconds: 0
# tpl:endif
